### ISSUE TITLE
pcd2las

### ISSUE THREAD

**Issue by Tejuwi** [murtiad/las2pcd#4]
How can we convert pcd2las? do you have any functions for this?. thanks

**Comment by murtiad** [comment]
Hi PradAI, I think it can be done by inversing some codes in this function. Another alternative is to use CloudCompare, but it's a separate software and may be problematic if you need to integrate pcd2las in your programme

**Comment by ferasboulala** [comment]
It is kind of late but [this](https://github.com/libLAS/libLAS/blob/master/test/sample/write.cpp) might help you out.
